name: Storybook Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: 1.4.3
          
      - name: Cache Bun packages
        uses: actions/cache@v6.1.0
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-1.4.3-${{ hashFiles('bun.lock') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Build Storybook
        run: bun run build-storybook